openapi: 3.1.0
info:
  title: Sample
  version: 0.0.0
tags:
  - name: sample
paths:
  /sample:
    get:
      operationId: SampleInterface_test1
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Additional'
      tags:
        - sample
    post:
      operationId: SampleInterface_test2
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unevaluated'
      tags:
        - sample
components:
  schemas:
    Additional:
      type: object
      required:
        - sample
      properties:
        sample:
          type: object
          unevaluatedProperties: {}
    Unevaluated:
      type: object
      required:
        - sample
      properties:
        sample:
          type: object
